import * as THREE from '/vendor/three.module.js';
import {OrbitControls} from '/vendor/OrbitControls.js';

const $=selector=>document.querySelector(selector);
const content=$('#content'),dialog=$('#dialog'),dialogBody=$('#dialogBody');
const state={health:null,assets:[],selected:new Set(),viewer:null,viewerToken:0};
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));

async function api(path,options){
  const response=await fetch(path,options);
  let data;
  try{data=await response.json()}catch{data={error:response.statusText}}
  if(!response.ok)throw new Error(data.error||response.statusText);
  return data;
}
function card(title,body){return `<div class="card"><h2>${title}</h2>${body}</div>`}
function show(title,html){dialogBody.innerHTML=`<h2>${esc(title)}</h2>${html}`;dialog.showModal()}
function assetUrl(id,version,fragment=''){return `/api/assets/${encodeURIComponent(id)}/file${version?`?version=${encodeURIComponent(version)}`:''}${fragment}`}

async function detail(id){
  try{
    const o=await api('/api/objects/'+encodeURIComponent(id));
    const fields=o.data?.fields||o.data||{};
    const page=o.data?.page;
    const open=o.source_asset_id?`<a class="action" target="_blank" rel="noopener" href="${assetUrl(o.source_asset_id,null,page?`#page=${page}`:'')}">打开登记原件${page?`第 ${page} 页`:''}</a>`:'';
    show(o.title,`<p><span class="tag">${esc(o.type)}</span> <span class="tag">${esc(o.status)}</span> <span class="tag">v${esc(o.version)}</span></p><p class="muted">来源资产：${esc(o.source_asset_id)} · ${esc(o.locator)}</p><h3>正文</h3><div class="source-body">${esc(o.body).replace(/\n/g,'<br>')}</div><h3>结构化字段</h3><table class="field-table">${Object.entries(fields).map(([key,value])=>`<tr><td>${esc(key)}</td><td>${esc(typeof value==='object'?JSON.stringify(value,null,2):value)||'<span class="muted">未知</span>'}</td></tr>`).join('')}</table><p class="muted">历史版本：${o.version_history.map(v=>`v${v.version} ${esc(v.content_hash).slice(0,12)}`).join('；')}</p><div class="space"></div>${open} <button class="primary" onclick="window.addPackage('${esc(o.id)}')">加入任务知识包</button>`);
  }catch(error){show('对象读取失败',`<div class="warn">${esc(error.message)}</div>`)}
}
async function assetDetail(id){
  try{
    const a=await api('/api/assets/'+encodeURIComponent(id));
    show(a.name,`<p><span class="tag">${esc(a.kind)}</span> <span class="tag">${esc(a.status)}</span> <span class="tag">v${esc(a.version)}</span></p><p class="mono">SHA-256 ${esc(a.sha256)}</p><p>${a.size.toLocaleString()} bytes</p><p class="muted">登记源路径：${esc(a.source_path)}</p><p class="muted">版本历史：${a.version_history.map(v=>`v${v.version} ${esc(v.sha256).slice(0,12)}`).join('；')}</p><a class="primary" target="_blank" rel="noopener" href="${assetUrl(a.id,a.version)}">打开登记副本</a>`);
  }catch(error){show('资产读取失败',`<div class="warn">${esc(error.message)}</div>`)}
}
window.addPackage=id=>{state.selected.add(id);show('已加入知识包',`<p>${esc(id)}</p><p class="muted">导出会锁定对象版本/内容哈希及全部案例依赖资产的版本/SHA-256；加入卡片本身不代表已建立工程适用性绑定。</p>`)};

const pages={
  home:async()=>{const h=state.health;content.innerHTML=`<div class="hero"><span class="tag">本地真实数据演示</span><h1>找资料、看懂资料、看模型</h1><p>来源、完整知识卡、关系和三维资产均以稳定 ID 相连。自动解析、可视化或规则检查都不代表工程批准。</p><button class="primary" data-go="search">开始检索</button></div><div class="space"></div><div class="grid g4">${card('当前知识对象',`<div class="num">${h.objects}</div><p class="muted">仅当前活动版本</p>`)}${card('登记资产',`<div class="num">${h.assets}</div><p class="muted">版本化副本 + SHA-256</p>`)}${card('本地有限元模型','<div class="num">3</div><p class="muted">plate / wingbox / framedeck</p>')}${card('DeepSeek',`<div class="num" style="font-size:20px">${esc(h.deepseek.label)}</div><p class="muted">${esc(h.deepseek.reason)}</p>`)}</div><div class="space"></div><div class="grid g3">${card('资料与依据','<p class="muted">全文检索返回正文、原件和页码/行号。</p><button class="action" data-go="search">找资料</button>')}${card('模型与案例','<p class="muted">STEP 用 OCCT WASM；BDF 用 pyNastran 并保留源节点/单元标识。</p><button class="action" data-go="models">看模型</button>')}${card('来源图谱','<p class="muted">对象和资产节点都可打开来源。</p><button class="action" data-go="graph">追溯来源</button>')}</div>`},
  search:async()=>{content.innerHTML=`<h1>资料与依据</h1><p class="muted">普通关键词安全转义后进入 FTS5；无命中再做字面 LIKE 回退。未启用语义 embedding。</p><div class="searchbar"><input id="q" placeholder="试试：DPW-W1、网格、Pazy"><select id="type"><option value="">全部类型</option>${['SourceSpan','术语卡','材料卡','网格策略卡','工况卡','Case'].map(x=>`<option>${x}</option>`).join('')}</select><button id="searchBtn" class="primary">检索</button></div><div class="space"></div><div id="results" class="list"></div>`;$('#searchBtn').onclick=runSearch;$('#q').onkeydown=e=>e.key==='Enter'&&runSearch();await runSearch()},
  cards:async()=>{content.innerHTML=`<h1>四类知识卡</h1><p class="muted">整条记录展示并可打开来源 CSV；选中不等于与某案例建立适用性绑定。</p><div class="tabs" id="cardTabs">${['材料卡','术语卡','网格策略卡','工况卡'].map((x,i)=>`<button class="${i?'':'active'}">${x}</button>`).join('')}</div><div id="cardList" class="list"></div>`;for(const button of $('#cardTabs').children)button.onclick=async()=>{[...button.parentElement.children].forEach(x=>x.classList.toggle('active',x===button));await loadCards(button.textContent)};await loadCards('材料卡')},
  models:async()=>{const assetModel={"cad-dpw-w1":"cad","cad-frame-step":"framecad","mesh-plate":"plate","result-plate":"plate","mesh-wingbox":"wingbox","mesh-framedeck":"framedeck"},initial=assetModel[new URLSearchParams(location.search).get('asset')]||'cad';content.innerHTML=`<h1>模型与案例</h1><p class="muted">五个对象相互独立：两个 STEP 仅作 CAD 浏览；plate 有公开 OP2；wingbox 与 framedeck 只有用户指定 BDF。frame.STEP 与 framedeck.bdf 的关系仅为名称线索，待确认。</p><div class="tabs" id="modelTabs"><button data-model="cad">CAD · DPW-W1</button><button data-model="framecad">CAD · frame</button><button data-model="plate">plate · BDF/OP2</button><button data-model="wingbox">wingbox · BDF</button><button data-model="framedeck">framedeck · BDF</button></div><div id="view" class="viewer"><div class="overlay" id="viewInfo">准备加载…</div><div class="controls"><button class="action" id="wire">线框</button><button class="action" id="reset">适配视角</button></div></div><div class="space"></div><div id="modelMeta" class="card"></div>`;for(const button of $('#modelTabs').children)button.onclick=()=>switchModel(button.dataset.model);await switchModel(initial)},
  graph:async()=>{const g=await api('/api/graph');content.innerHTML=`<h1>知识图谱</h1><p class="muted">点击对象查看正文；点击资产查看版本、哈希并打开登记副本。</p><div class="searchbar"><input id="graphQ" placeholder="输入对象名称，如 wingbox、DPW"><select id="graphType"><option value="">全部类型</option><option>Case</option><option>engineering_asset</option><option>材料卡</option><option>工况卡</option></select><button id="graphSearch" class="primary">定位并展开</button><button id="graphReset" class="action">主链</button></div><div class="space"></div><svg class="graph" id="graph" viewBox="0 0 1100 600"></svg><div class="space"></div><div id="edgeInfo" class="card">选择一条关系查看依据。</div>`;let current=g;const render=()=>{const type=$('#graphType').value;drawGraph(type?{nodes:current.nodes.filter(n=>n.type===type),edges:current.edges}:current)};render();$('#graphType').onchange=render;$('#graphSearch').onclick=async()=>{const q=$('#graphQ').value.trim();if(!q)return;const s=await api('/api/search?q='+encodeURIComponent(q));if(!s.items.length){$('#edgeInfo').innerHTML='<div class="warn">没有找到对象。</div>';return}current=await api('/api/graph?seed='+encodeURIComponent(s.items[0].id));render();$('#edgeInfo').innerHTML=`<b>已定位：</b>${esc(s.items[0].title)} · 展开一跳关系`};$('#graphReset').onclick=async()=>{current=await api('/api/graph');render()}},
  package:async()=>{content.innerHTML=`<h1>任务知识包</h1><div class="grid g2">${card('已选对象',`<div id="selected" class="mono">${[...state.selected].map(esc).join('\n')||'尚未选择；请从搜索或知识卡加入。'}</div><div class="space"></div><button id="buildPkg" class="primary">生成版本锁定 JSON</button>`)}${card('执行边界','<p class="muted">对象类型齐全并不等于可执行。案例必须声明经审核的材料/工况绑定、单位、求解配置和验证门，且所有依赖资产均被锁定。</p><div id="pkgState" class="warn">待检查</div>')}</div><div class="space"></div><pre id="pkg" class="card mono"></pre>`;$('#buildPkg').onclick=buildPackage},
  quality:async()=>{const a=await api('/api/assets');content.innerHTML=`<h1>导入与质量</h1><div class="ok">源文件只读；登记副本按资产版本和 SHA-256 保存，源变化生成新版本，历史不覆盖。</div><div class="space"></div>${card('登记资产',`<div class="list">${a.items.map(x=>`<div class="item"><div><b>${esc(x.name)}</b><small>${esc(x.status)} · v${x.version} · ${x.size.toLocaleString()} bytes</small><small class="mono">SHA-256 ${esc(x.sha256)}</small></div><button class="action" data-asset="${esc(x.id)}">查看/打开</button></div>`).join('')}</div>`)}<div class="space"></div>${card('范围边界','<p><code>D:\\知识库</code> 只完成路径级只读盘点；结构化导入限登记样本。Semantica 仍是独立 GraphBuilder 探针，并非当前导入管线。解析成功 ≠ 工程复核 ≠ 工程批准。</p>')}`;document.querySelectorAll('[data-asset]').forEach(button=>button.onclick=()=>assetDetail(button.dataset.asset))},
  assistant:async()=>{const d=state.health.deepseek;content.innerHTML=`<div class="assistant-head"><div><h1>DSH 智能助手</h1><p class="muted">原生 DSH Web 已直接嵌入；会话、消息流、模型配置、CAE 模式和工具调用均由本地 DSH 提供。</p></div><div class="${d.state==='call_passed'?'ok':'warn'} assistant-model"><b>${esc(d.label)}</b><span>${esc(d.reason)}</span></div></div><div class="assistant-toolbar"><span id="dshEmbedState" class="tag">检查本地 DSH…</span><button id="reloadDsh" class="action">重新载入界面</button><details><summary>技术状态</summary><div class="tech-fold"><p>隔离 HOME：<code>runtime/dsh-home</code>；新会话默认 CAE 模式。</p><p>知识 MCP 与 Viewer MCP 的可用性分别验证；模型调用状态与 MCP 状态分开。</p><p>嵌入使用 DSH 原生令牌换签名 Cookie，之后 HTTP/WebSocket 直连 <code>127.0.0.1:3088</code>。令牌不写入页面正文、日志或报告。</p><p>模型回复、工具成功或求解器退出码都不替代工程审核与批准。</p></div></details></div><div class="dsh-frame-wrap"><iframe id="dshFrame" title="DSH 原生智能助手" referrerpolicy="same-origin" allow="clipboard-read; clipboard-write"></iframe><div id="dshFrameError" class="warn dsh-frame-error" hidden></div></div>`;const frame=$('#dshFrame'),status=$('#dshEmbedState'),error=$('#dshFrameError');const load=async()=>{error.hidden=true;status.textContent='正在连接原生 DSH…';try{const runtime=await api('/api/dsh/status');if(runtime.state!=='ready')throw new Error(runtime.error||`DSH 状态：${runtime.state}`);frame.src='/dsh/embed';frame.onload=()=>{status.textContent='原生 DSH 已嵌入 · WebSocket 由 DSH 管理'}}catch(exc){status.textContent='DSH 未就绪';error.hidden=false;error.textContent='无法嵌入 DSH：'+exc.message}};$('#reloadDsh').onclick=()=>{frame.src='about:blank';load()};await load()}
};

async function runSearch(){
  const q=$('#q')?.value||'',type=$('#type')?.value||'',target=$('#results');
  try{const d=await api(`/api/search?q=${encodeURIComponent(q)}&type=${encodeURIComponent(type)}`);target.innerHTML=d.items.length?d.items.map(x=>`<div class="item"><div><span class="tag">${esc(x.type)}</span> <b>${esc(x.title)}</b><small>${esc(x.body).slice(0,180)}</small><small>来源 ${esc(x.source_asset_id)} · ${esc(x.locator)} · v${esc(x.version)}</small></div><button class="action" data-id="${esc(x.id)}">查看正文/原件</button></div>`).join(''):'<div class="warn">没有命中。此状态表示知识缺失或关键词不匹配，不会生成回答。</div>';document.querySelectorAll('[data-id]').forEach(button=>button.onclick=()=>detail(button.dataset.id))}catch(error){target.innerHTML=`<div class="warn">检索失败：${esc(error.message)}</div>`}
}
async function loadCards(type){const target=$('#cardList');try{const d=await api('/api/search?type='+encodeURIComponent(type));target.innerHTML=d.items.map(x=>`<div class="item"><div><b>${esc(x.title)}</b><small>${esc(x.status)} · v${esc(x.version)}</small><small>来源 ${esc(x.source_asset_id)} · ${esc(x.locator)}</small></div><button class="action" data-id="${esc(x.id)}">完整卡/原件</button></div>`).join('');document.querySelectorAll('[data-id]').forEach(button=>button.onclick=()=>detail(button.dataset.id))}catch(error){target.innerHTML=`<div class="warn">卡片读取失败：${esc(error.message)}</div>`}}

function disposeViewer(){
  state.viewerToken++;
  const v=state.viewer;if(!v)return;
  if(v.frame)cancelAnimationFrame(v.frame);
  v.controls.dispose();
  v.scene.traverse(obj=>{if(obj.geometry)obj.geometry.dispose();if(obj.material){const materials=Array.isArray(obj.material)?obj.material:[obj.material];materials.forEach(material=>material.dispose())}});
  v.renderer.dispose();if(v.renderer.forceContextLoss)v.renderer.forceContextLoss();v.renderer.domElement.remove();
  window.removeEventListener('resize',v.resize);state.viewer=null;
}
function makeScene(){
  disposeViewer();const token=state.viewerToken,el=$('#view'),scene=new THREE.Scene();scene.background=new THREE.Color(0x161a24);
  const cam=new THREE.PerspectiveCamera(45,Math.max(el.clientWidth,1)/Math.max(el.clientHeight,1),.01,1e9),renderer=new THREE.WebGLRenderer({antialias:true});
  renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(el.clientWidth,el.clientHeight);el.appendChild(renderer.domElement);
  const controls=new OrbitControls(cam,renderer.domElement);scene.add(new THREE.HemisphereLight(0xffffff,0x333344,2.2));const light=new THREE.DirectionalLight(0xffffff,2);light.position.set(1,2,3);scene.add(light);const group=new THREE.Group();scene.add(group);
  const fit=()=>{const box=new THREE.Box3().setFromObject(group);if(box.isEmpty())return;const size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3()),max=Math.max(size.x,size.y,size.z)||1;controls.target.copy(center);cam.position.copy(center).add(new THREE.Vector3(max*1.2,-max*1.4,max*.9));cam.near=Math.max(max/10000,.0001);cam.far=max*100;cam.updateProjectionMatrix();controls.update()};
  const resize=()=>{if(state.viewer?.token!==token)return;cam.aspect=Math.max(el.clientWidth,1)/Math.max(el.clientHeight,1);cam.updateProjectionMatrix();renderer.setSize(el.clientWidth,el.clientHeight)};window.addEventListener('resize',resize);
  const v={token,el,scene,cam,renderer,controls,group,fit,resize,frame:null};state.viewer=v;
  const animate=()=>{if(state.viewer!==v||state.viewerToken!==token)return;v.frame=requestAnimationFrame(animate);controls.update();renderer.render(scene,cam)};animate();return v;
}
async function switchModel(name){
  document.querySelectorAll('#modelTabs button').forEach(button=>button.classList.toggle('active',button.dataset.model===name));const v=makeScene();
  try{if(name==='cad')await loadCad(v,'cad-dpw-w1','DPW-W1 公开 CAD 浏览样本',false);else if(name==='framecad')await loadCad(v,'cad-frame-step','用户本地 frame STEP 浏览样本',true);else await loadMesh(v,name)}catch(error){if(state.viewer===v){$('#viewInfo').textContent='模型加载失败：'+error.message;$('#modelMeta').innerHTML=`<div class="warn"><b>STEP/模型加载未完成</b><br>${esc(error.stack||error.message)}</div>`}}
  if(state.viewer!==v)return;$('#reset').onclick=v.fit;$('#wire').onclick=()=>v.group.traverse(obj=>{if(obj.material){const materials=Array.isArray(obj.material)?obj.material:[obj.material];materials.forEach(material=>{if('wireframe' in material)material.wireframe=!material.wireframe})}});
}
async function loadCad(v,assetId,title,relationPending){
  const started=performance.now();$('#viewInfo').textContent='OCCT WASM 正在读取 STEP…';const response=await fetch('/api/assets/'+encodeURIComponent(assetId)+'/file');if(!response.ok)throw new Error(`STEP 请求失败 ${response.status}`);const bytes=new Uint8Array(await response.arrayBuffer());if(state.viewer!==v)return;
  const occt=await window.occtimportjs({locateFile:()=>'/vendor/occt-import-js.wasm'});if(state.viewer!==v)return;const result=occt.ReadStepFile(bytes,null);if(!result.success)throw new Error('OCCT 返回 success=false');let verts=0,tris=0;
  for(const item of result.meshes){const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute(item.attributes.position.array,3));if(item.attributes.normal)geometry.setAttribute('normal',new THREE.Float32BufferAttribute(item.attributes.normal.array,3));geometry.setIndex(item.index.array);const color=item.color?new THREE.Color(...item.color):new THREE.Color(0x9d8dde);v.group.add(new THREE.Mesh(geometry,new THREE.MeshStandardMaterial({color,metalness:.15,roughness:.65,side:THREE.DoubleSide})));verts+=item.attributes.position.array.length/3;tris+=item.index.array.length/3}
  const elapsed=Math.round(performance.now()-started);v.fit();$('#viewInfo').textContent=`真实 STEP · ${result.meshes.length} 网格块 · ${verts.toLocaleString()} 顶点 · ${tris.toLocaleString()} 三角形 · ${elapsed.toLocaleString()} ms`;$('#modelMeta').innerHTML=`<h2>${esc(title)}</h2><p>浏览器实际调用 OCCT WASM；下载、解析和建模总耗时约 ${elapsed.toLocaleString()} ms。可鼠标旋转、滚轮缩放和适配视角。</p>${relationPending?'<div class="warn">与 framedeck.bdf 的关系仅来自文件名近似，当前状态：待确认。</div>':''}<p>这不是可执行仿真案例，未绑定材料、工况、单位、求解器或结果。</p><p><button class="action" data-asset="${esc(assetId)}">查看来源资产</button></p>`;$('#modelMeta [data-asset]').onclick=()=>assetDetail(assetId);
}
async function loadMesh(v,name){
  $('#viewInfo').textContent=`正在读取 ${name} BDF 派生网格…`;const mesh=await api('/api/mesh/'+encodeURIComponent(name));if(state.viewer!==v)return;
  let result=null;if(name==='plate')result=await api('/api/result/plate');if(state.viewer!==v)return;
  const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute(mesh.positions,3));if(mesh.triangle_indices.length)geometry.setIndex(mesh.triangle_indices);geometry.computeVertexNormals();
  let material;
  if(result){const values=result.values||[],finite=values.filter(value=>value!=null),lo=finite.length?Math.min(...finite):0,hi=finite.length?Math.max(...finite):0,colors=[];for(let i=0;i<mesh.node_ids.length;i++){const t=hi>lo&&values[i]!=null?(values[i]-lo)/(hi-lo):.25,c=new THREE.Color().setHSL((1-t)*.66,1,.5);colors.push(c.r,c.g,c.b)}geometry.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));material=new THREE.MeshStandardMaterial({vertexColors:true,side:THREE.DoubleSide,roughness:.75})}else material=new THREE.MeshStandardMaterial({color:name==='framedeck'?0x6cb7b2:0x9d8dde,side:THREE.DoubleSide,roughness:.75});
  if(mesh.triangle_indices.length)v.group.add(new THREE.Mesh(geometry,material));
  if(mesh.line_indices?.length){const lineGeometry=new THREE.BufferGeometry();lineGeometry.setAttribute('position',new THREE.Float32BufferAttribute(mesh.positions,3));lineGeometry.setIndex(mesh.line_indices);v.group.add(new THREE.LineSegments(lineGeometry,new THREE.LineBasicMaterial({color:0xffc46b})))}
  v.fit();const resultLabel=result?` · OP2 ${esc(result.variable)} / Subcase ${result.subcase??'未知'}`:' · 无登记结果';$('#viewInfo').textContent=`真实 BDF · ${mesh.node_count.toLocaleString()} 节点 · ${mesh.element_count.toLocaleString()} 单元 · ${mesh.render_triangle_count.toLocaleString()} 表面三角形${resultLabel}`;
  const asset=mesh.asset_id||`mesh-${name}`,resultText=result?`颜色来自 OP2 ${esc(result.variable)}，范围 ${result.min?.toExponential(4)} ～ ${result.max?.toExponential(4)}，单位：${esc(result.unit)}。`:'未提供或登记求解结果；源单位、材料/载荷适用性均待确认。';
  $('#modelMeta').innerHTML=`<h2>${esc(name)} 有限元模型</h2><p>${resultText}</p><p>解析器：${esc(mesh.parser)}；${esc(mesh.surface_method)}。渲染节点 ${mesh.render_node_count.toLocaleString()}，边界面 ${mesh.boundary_face_count.toLocaleString()}，线单元 ${mesh.render_line_count.toLocaleString()}。</p>${mesh.gaps?.length?`<div class="warn">${mesh.gaps.map(esc).join('；')}</div>`:''}<p class="mono">源 SHA-256 ${esc(mesh.source_sha256)}</p><button class="action" data-asset="${esc(asset)}">查看来源资产</button>`;$('#modelMeta [data-asset]').onclick=()=>assetDetail(asset);
}

function drawGraph(g){
  const svg=$('#graph'),W=1100,H=600,ns='http://www.w3.org/2000/svg',map=new Map();svg.innerHTML='';svg.setAttribute('viewBox',`0 0 ${W} ${H}`);g.nodes.forEach((n,i)=>{const angle=i/Math.max(g.nodes.length,1)*Math.PI*2;map.set(n.id,{...n,x:W/2+Math.cos(angle)*Math.min(360,120+g.nodes.length*18),y:H/2+Math.sin(angle)*Math.min(210,80+g.nodes.length*12)})});
  for(const e of g.edges){const a=map.get(e.source_id),b=map.get(e.target_id);if(!a||!b)continue;const line=document.createElementNS(ns,'line');line.setAttribute('x1',a.x);line.setAttribute('y1',a.y);line.setAttribute('x2',b.x);line.setAttribute('y2',b.y);line.classList.add('edge');line.onclick=()=>{$('#edgeInfo').innerHTML=`<h2>${esc(e.relation)}</h2><p><b>方法：</b>${esc(e.method)}　<b>状态：</b>${esc(e.status)}</p><p><b>依据：</b>${esc(e.evidence)}</p><p class="mono">${esc(e.source_id)} → ${esc(e.target_id)}</p>`};svg.appendChild(line)}
  for(const n of map.values()){const group=document.createElementNS(ns,'g');group.classList.add('node');group.setAttribute('transform',`translate(${n.x},${n.y})`);group.innerHTML=`<circle r="34" fill="${n.type==='Case'?'#6d51c7':n.type==='engineering_asset'?'#2393a6':'#9b87d3'}"></circle><text text-anchor="middle" y="52">${esc(n.title).slice(0,22)}</text>`;group.onclick=()=>n.node_kind==='asset'?assetDetail(n.id):detail(n.id);svg.appendChild(group)}
  let vb={x:0,y:0,w:W,h:H},drag=null;const apply=()=>svg.setAttribute('viewBox',`${vb.x} ${vb.y} ${vb.w} ${vb.h}`);svg.onwheel=event=>{event.preventDefault();const factor=event.deltaY>0?1.15:.87;vb.x+=vb.w*(1-factor)/2;vb.y+=vb.h*(1-factor)/2;vb.w*=factor;vb.h*=factor;apply()};svg.onpointerdown=event=>{drag={x:event.clientX,y:event.clientY,vx:vb.x,vy:vb.y};svg.setPointerCapture(event.pointerId)};svg.onpointermove=event=>{if(!drag)return;vb.x=drag.vx-(event.clientX-drag.x)*vb.w/svg.clientWidth;vb.y=drag.vy-(event.clientY-drag.y)*vb.h/svg.clientHeight;apply()};svg.onpointerup=()=>drag=null;
}
async function buildPackage(){try{const d=await api('/api/package',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({object_ids:[...state.selected]})});$('#pkg').textContent=JSON.stringify(d,null,2);$('#pkgState').className=d.executable?'ok':'warn';$('#pkgState').textContent=d.executable?'执行就绪检查通过（仍不等于工程批准）':'不可执行：'+(d.gaps.join('；')||'未选择案例')}catch(error){$('#pkgState').className='warn';$('#pkgState').textContent='生成失败：'+error.message}}
async function go(name){if(!pages[name])name='home';if(name!=='models')disposeViewer();if(location.hash!==`#${name}`)history.replaceState(null,'',`#${name}`);document.querySelectorAll('#nav button').forEach(button=>button.classList.toggle('active',button.dataset.page===name));$('#pageTitle').textContent=document.querySelector(`[data-page="${name}"]`)?.textContent||name;try{await pages[name]()}catch(error){content.innerHTML=`<div class="warn">页面加载失败：${esc(error.stack||error.message)}</div>`}document.querySelectorAll('[data-go]').forEach(button=>button.onclick=()=>go(button.dataset.go))}
for(const button of document.querySelectorAll('#nav button'))button.onclick=()=>go(button.dataset.page);
window.addEventListener('hashchange',()=>go(location.hash.slice(1)||'home'));
try{state.health=await api('/api/health');state.assets=(await api('/api/assets')).items;$('#status').textContent=`服务在线 · ${state.health.objects} 个当前知识对象`;await go(location.hash.slice(1)||'home')}catch(error){$('#status').textContent='服务异常';content.innerHTML=`<div class="warn">${esc(error.stack||error.message)}</div>`}
