from pathlib import Path
p=Path('D:/zhishiku/desktop-framework/src/static/app.js')
s=p.read_text('utf-8')
s=s.replace("<small>${esc((r.data.summary||'用途待补充').slice(0,85))}</small>","<small>${esc((r.data.summary||'用途待补充').slice(0,140))}</small>${r.evidence?.length?`<details><summary>正文命中 · ${r.evidence.length} 处</summary>${r.evidence.map(e=>`<p>${esc(e.text.slice(0,500))}<br><a href=\"${esc(e.url)}\" target=\"_blank\">打开原件 · 第 ${e.page} 页</a></p>`).join('')}</details>`:''}")
start=s.index(" const search=async()=>")
end=s.index(" }else if(['cards'",start)
s=s[:start]+''' const stats=await api('/api/collection');
 $('#search-form').insertAdjacentHTML('beforeend',`<select id="category"><option value="">全部分类</option>${stats.categories.map(x=>`<option>${esc(x.category)}</option>`).join('')}</select>`);
 $('#query').placeholder='试试：什么是飞机机身 / 机翼 / 机身框静强度仿真';
 let offset=0;const search=async()=>{try{let r=await api('/api/search?'+new URLSearchParams({q:$('#query').value,type:$('#search-type').value,analysis_type:$('#analysis').value,category:$('#category').value,limit:30,offset}));$('#search-info').textContent=`${r.total} 条匹配 · 正文页码与完整卡片联合检索 · 第 ${Math.floor(offset/30)+1} 页`;
 const terms=r.items.filter(x=>x.type==='term').slice(0,2);
 $('#results').innerHTML=(terms.length?`<div class="banner"><b>先看定义 · 候选资料摘录</b>${terms.map(x=>`<p><b>${esc(x.title)}</b><br>${esc(x.data.definition)}<br><button data-open="${x.id}">查看整卡与来源</button></p>`).join('')}</div>`:'')+table(r.items)+(r.message?`<div class="banner">${esc(r.message)} ${button('登记缺口','data-new="gap"')}</div>`:'')+`<div class="actions"><button id="prev-page" ${offset===0?'disabled':''}>上一页</button><button id="next-page" ${offset+30>=r.total?'disabled':''}>下一页</button></div>`;
 $('#prev-page').onclick=()=>{offset=Math.max(0,offset-30);search()};$('#next-page').onclick=()=>{offset+=30;search()};bind()}catch(e){$('#results').innerHTML=`<div class="banner warning">检索服务异常：${esc(e.message)}。此状态不能解释为知识不存在。</div>`}};$('#search-form').onsubmit=e=>{e.preventDefault();offset=0;search()};await search();
''' + s[end:]
s=s.replace("const records=(await api('/api/search?limit=500')).items.filter(r=>def[2].includes(r.type));$('#records').innerHTML=table(records);","let recordOffset=0; const loadRecords=async()=>{const batches=await Promise.all(def[2].map(t=>api('/api/search?'+new URLSearchParams({type:t,limit:50,offset:recordOffset}))));const records=batches.flatMap(r=>r.items);$('#records').innerHTML=table(records)+`<div class=\"actions\"><button id=\"record-prev\" ${recordOffset===0?'disabled':''}>上一页</button><button id=\"record-next\" ${batches.every(r=>recordOffset+50>=r.total)?'disabled':''}>下一页</button><span>各类型共 ${batches.reduce((n,r)=>n+r.total,0)} 条</span></div>`;$('#record-prev').onclick=()=>{recordOffset=Math.max(0,recordOffset-50);loadRecords()};$('#record-next').onclick=()=>{recordOffset+=50;loadRecords()};bind()};await loadRecords();")
s=s.replace("${t.fields.map(f=>`<div class=\"detail-field\"><strong>${f.label}</strong><div>${esc(Array.isArray(o.data[f.key])?JSON.stringify(o.data[f.key],null,2):o.data[f.key]||'待补充')}</div></div>`).join('')}","${t.fields.filter(f=>f.key!=='original_record').map(f=>`<div class=\"detail-field\"><strong>${f.label}</strong><div>${esc(Array.isArray(o.data[f.key])?JSON.stringify(o.data[f.key],null,2):o.data[f.key]||'待补充')}</div></div>`).join('')}<details><summary>原始结构化记录（供智能体读取）</summary><pre>${esc(o.data.original_record||'无')}</pre></details><div id=\"source-evidence\"></div>")
s=s.replace("if(!$('#detail').open)$('#detail').showModal()}catch(e)","const evidence=await api('/api/objects/'+id+'/evidence');$('#source-evidence').innerHTML=evidence.length?`<details><summary>读取正文 · 前 ${evidence.length} 段（完整内容可检索）</summary>${evidence.map(e=>`<p><a href=\"/api/model-assets/${e.file_id}/file#page=${e.page}\" target=\"_blank\">原件第 ${e.page} 页 / 表</a></p><pre>${esc(e.text)}</pre>`).join('')}</details>`:'';if(!$('#detail').open)$('#detail').showModal()}catch(e)")
s=s.replace('为未来的智能体提供完整、可追溯的知识。','为智能体提供完整、可追溯的知识接口与 JSON 导出。')
s=s.replace('模板已经准备好，内容由你逐步积累','完整卡片、原始资料与案例分别保存')
s=s.replace('按名称、正文、字段和术语别名检索；明确区分未命中与服务异常。','自然语言关键词、完整卡片与原文页段联合检索；点击正文命中可打开原件。')
s=s.replace('先准备结构与来源，再逐步填充真实资料。业务数据独立保存，不进入 EXE。','查看采集、正文提取与扫描缺口；原件和索引独立于程序保存。')
s=s.replace('<td>原始语料 / 切片</td><td>未自动导入</td>','<td>原始语料 / 切片</td><td>已接入，见下方采集统计</td>')
s=s.replace("$('#import-json').onclick=", "const collected=await api('/api/collection');page.insertAdjacentHTML('beforeend',`<div class=\"panel\"><h2>原始资料与提取质量</h2><p>${collected.sources} 份去重原件 · ${collected.chunks} 个正文片段 · ${collected.indexed_pages} / ${collected.pages} 页已提取文字</p><table class=\"table\">${collected.extraction.map(x=>`<tr><td>${esc(x.extraction)}</td><td>${x.count}</td></tr>`).join('')}</table><p>needs_ocr：扫描页待识别；partial_needs_ocr：部分扫描页；format_pending：格式待解析；model_registered：模型原件已登记。未提取正文的资料可按名称找到并打开原件。</p><p>${esc(collected.training)}</p></div>`);$('#import-json').onclick=")
p.write_text(s,encoding='utf-8')
